# Github Actions Workflow file that builds and pushes the docker images.
name: practicalgitops.app
env:
 # DOCKERHUB_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/react-app"
  DOCKERFILE_PATH: app

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "!**/README.md"

# Job declaration starts.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: docker build -t sk224400/reactjs-app .
      - name: Publish image to docker hub
        run: docker push sk224400/reactjs-app:latest   
  
      
