name: Deploy React Native App to EC2 
env:
 # DOCKERHUB_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/sk224400"
  DOCKERFILE_PATH: app

on:
 push:
   branches:
     - main
   paths:
     - "app/**"
     - "!** /README.md"


 # Job declaration starts here
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t my-react-native-app .
          docker tag my-react-native-app ${{ secrets.DOCKERHUB_USERNAME }}/my-react-native-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-react-native-app:latest 
      
