# Github Actions Workflow file that builds and pushes the docker images.
name: Deploy react app to ECS
env:
  # DOCKERHUB_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/practicalgitops"
  DOCKERFILE_PATH: app

on:
  push:
    branches:
      - main
    paths:
      - ".github/"
      - "app/**"
      - "!**/README.md"

# Job declaration starts.
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ github.sha }}
      
