name: Build and Push Docker Image

env:
 #DOCKERHUB_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/my-react-app"
  DOCKERFILE_PATH: app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build the Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "${{ env.DOCKERFILE_PATH}}"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest

      # Step 5: Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest
  
      
